name: Territory-Conquest-Chat
version: '${project.version}'
main: thedavid.territoryconquestchat.Territory_Conquest_Chat
api-version: 1.19
soft depends: [DiscordSRV,ProtocolLib, PlaceholderAPI]
commands:
  channel:
    aliases:
      - "ch"
    description: "choose channel to listen"
    usage: "/ch <channel>"
permissions:
  tcc.color:
    description: "can use color in chat"
    default: op
  tcc.decoration:
    description: "can use decoration in chat"
    default: op


